# Generated by Django 3.0 on 2023-10-24 17:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default=1000, max_length=25)),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupees'), ('USD', 'US Dollars')], default='INR', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_id', models.IntegerField(default=100)),
                ('customer_name', models.CharField(default='null', max_length=50)),
                ('customer_email', models.EmailField(default='null', max_length=50)),
                ('customer_phone', models.CharField(default='null', max_length=15)),
                ('order_expiry_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_note', models.TextField(max_length=100)),
            ],
        ),
    ]
