# Generated by Django 3.0 on 2023-10-21 21:45

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('INR', 'Indian Rupees'), ('USD', 'US Dollars')], default='INR', max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_id',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(default='null', max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='order_expiry_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='order_note',
            field=models.TextField(default='test_order', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(limit_value=3)]),
        ),
    ]
